package com.funkyFunctor.pdfFormFiller

import zio.ZIO

import java.io.InputStream
import com.funkyFunctor.pdfFormFiller.model.FormParameters._

object W2G {
  val templateClasspathLocation = "w2g.pdf"

  def pdfTemplate: ZIO[Any, Throwable, InputStream] = {
    ZIO {
      val result = getClass.getClassLoader.getResourceAsStream(templateClasspathLocation)
       if (result != null)
         result
       else throw new Exception(s"File '$templateClasspathLocation' could not be loaded from classpath")
    }
  }

  val fieldsMapping: Map[String, String] = Map(
    "topmostSubform[0].Copy1[0].Col_Left[0].f1_02[0]"           -> PAYER_ADDRESS,
    "topmostSubform[0].Copy1[0].Col_Left[0].f1_03[0]"           -> PAYER_TAX_ID,
    "topmostSubform[0].Copy1[0].Col_Left[0].f1_04[0]"           -> PAYER_TEL_NB,
    "topmostSubform[0].Copy1[0].Col_Left[0].f1_05[0]"           -> WINNER_NAME,
    "topmostSubform[0].Copy1[0].Col_Left[0].f1_06[0]"           -> WINNER_STREET_ADDRESS,
    "topmostSubform[0].Copy1[0].Col_Left[0].f1_07[0]"           -> WINNER_CITY_TOWN,
    "topmostSubform[0].Copy1[0].Col_Right[0].Box15[0].f1_22[0]" -> STATE_TAX_WITHHELD,
    "topmostSubform[0].Copy1[0].Col_Right[0].Box17[0].f1_24[0]" -> LOCAL_TAX_WITHHELD,
    "topmostSubform[0].Copy1[0].Col_Right[0].Box1[0].f1_08[0]"  -> REPORTABLE_WINNINGS,
    "topmostSubform[0].Copy1[0].Col_Right[0].Box7[0].f1_14[0]"  -> WINNINGS_FROM_IDENTICAL_WAGERS,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_09[0]"          -> DATE_WON,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_10[0]"          -> WAGER_TYPE,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_11[0]"          -> FEDERAL_TAX_WITHHELD,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_12[0]"          -> TRANSACTION,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_13[0]"          -> RACE,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_15[0]"          -> CASHIER,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_16[0]"          -> WINNER_SSN,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_17[0]"          -> WINDOW,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_18[0]"          -> FIRST_ID,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_19[0]"          -> SECOND_ID,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_20[0]"          -> STATE_ID_NO,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_21[0]"          -> STATE_WINNINGS,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_23[0]"          -> LOCAL_WINNINGS,
    "topmostSubform[0].Copy1[0].Col_Right[0].f1_25[0]"          -> LOCALITY_NAME,
    "topmostSubform[0].Copy1[0].Copy1Header[0].f1_01[0]"        -> CALENDAR_YEAR,
    "topmostSubform[0].Copy2[0].Col_Left[0].f1_02[0]"           -> PAYER_ADDRESS,
    "topmostSubform[0].Copy2[0].Col_Left[0].f1_03[0]"           -> PAYER_TAX_ID,
    "topmostSubform[0].Copy2[0].Col_Left[0].f1_04[0]"           -> PAYER_TEL_NB,
    "topmostSubform[0].Copy2[0].Col_Left[0].f1_05[0]"           -> WINNER_NAME,
    "topmostSubform[0].Copy2[0].Col_Left[0].f1_06[0]"           -> WINNER_STREET_ADDRESS,
    "topmostSubform[0].Copy2[0].Col_Left[0].f1_07[0]"           -> WINNER_CITY_TOWN,
    "topmostSubform[0].Copy2[0].Col_Right[0].Box15[0].f1_22[0]" -> STATE_TAX_WITHHELD,
    "topmostSubform[0].Copy2[0].Col_Right[0].Box17[0].f1_24[0]" -> LOCAL_TAX_WITHHELD,
    "topmostSubform[0].Copy2[0].Col_Right[0].Box1[0].f1_08[0]"  -> REPORTABLE_WINNINGS,
    "topmostSubform[0].Copy2[0].Col_Right[0].Box7[0].f1_14[0]"  -> WINNINGS_FROM_IDENTICAL_WAGERS,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_09[0]"          -> DATE_WON,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_10[0]"          -> WAGER_TYPE,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_11[0]"          -> FEDERAL_TAX_WITHHELD,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_12[0]"          -> TRANSACTION,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_13[0]"          -> RACE,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_15[0]"          -> CASHIER,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_16[0]"          -> WINNER_SSN,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_17[0]"          -> WINDOW,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_18[0]"          -> FIRST_ID,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_19[0]"          -> SECOND_ID,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_20[0]"          -> STATE_ID_NO,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_21[0]"          -> STATE_WINNINGS,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_23[0]"          -> LOCAL_WINNINGS,
    "topmostSubform[0].Copy2[0].Col_Right[0].f1_25[0]"          -> LOCALITY_NAME,
    "topmostSubform[0].Copy2[0].Copy2Header[0].f1_01[0]"        -> CALENDAR_YEAR,
    "topmostSubform[0].CopyA[0].Col_Left[0].f1_02[0]"           -> PAYER_ADDRESS,
    "topmostSubform[0].CopyA[0].Col_Left[0].f1_03[0]"           -> PAYER_TAX_ID,
    "topmostSubform[0].CopyA[0].Col_Left[0].f1_04[0]"           -> PAYER_TEL_NB,
    "topmostSubform[0].CopyA[0].Col_Left[0].f1_05[0]"           -> WINNER_NAME,
    "topmostSubform[0].CopyA[0].Col_Left[0].f1_06[0]"           -> WINNER_STREET_ADDRESS,
    "topmostSubform[0].CopyA[0].Col_Left[0].f1_07[0]"           -> WINNER_CITY_TOWN,
    "topmostSubform[0].CopyA[0].Col_Right[0].Box15[0].f1_22[0]" -> STATE_TAX_WITHHELD,
    "topmostSubform[0].CopyA[0].Col_Right[0].Box17[0].f1_24[0]" -> LOCAL_TAX_WITHHELD,
    "topmostSubform[0].CopyA[0].Col_Right[0].Box1[0].f1_08[0]"  -> REPORTABLE_WINNINGS,
    "topmostSubform[0].CopyA[0].Col_Right[0].Box7[0].f1_14[0]"  -> WINNINGS_FROM_IDENTICAL_WAGERS,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_09[0]"          -> DATE_WON,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_10[0]"          -> WAGER_TYPE,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_11[0]"          -> FEDERAL_TAX_WITHHELD,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_12[0]"          -> TRANSACTION,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_13[0]"          -> RACE,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_15[0]"          -> CASHIER,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_16[0]"          -> WINNER_SSN,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_17[0]"          -> WINDOW,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_18[0]"          -> FIRST_ID,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_19[0]"          -> SECOND_ID,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_20[0]"          -> STATE_ID_NO,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_21[0]"          -> STATE_WINNINGS,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_23[0]"          -> LOCAL_WINNINGS,
    "topmostSubform[0].CopyA[0].Col_Right[0].f1_25[0]"          -> LOCALITY_NAME,
    "topmostSubform[0].CopyA[0].CopyAHeader[0].f1_01[0]"        -> CALENDAR_YEAR,
    "topmostSubform[0].CopyB[0].Col_Left[0].f1_02[0]"           -> PAYER_ADDRESS,
    "topmostSubform[0].CopyB[0].Col_Left[0].f1_03[0]"           -> PAYER_TAX_ID,
    "topmostSubform[0].CopyB[0].Col_Left[0].f1_04[0]"           -> PAYER_TEL_NB,
    "topmostSubform[0].CopyB[0].Col_Left[0].f1_05[0]"           -> WINNER_NAME,
    "topmostSubform[0].CopyB[0].Col_Left[0].f1_06[0]"           -> WINNER_STREET_ADDRESS,
    "topmostSubform[0].CopyB[0].Col_Left[0].f1_07[0]"           -> WINNER_CITY_TOWN,
    "topmostSubform[0].CopyB[0].Col_Right[0].Box15[0].f1_22[0]" -> STATE_TAX_WITHHELD,
    "topmostSubform[0].CopyB[0].Col_Right[0].Box17[0].f1_24[0]" -> LOCAL_TAX_WITHHELD,
    "topmostSubform[0].CopyB[0].Col_Right[0].Box1[0].f1_08[0]"  -> REPORTABLE_WINNINGS,
    "topmostSubform[0].CopyB[0].Col_Right[0].Box7[0].f1_14[0]"  -> WINNINGS_FROM_IDENTICAL_WAGERS,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_09[0]"          -> DATE_WON,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_10[0]"          -> WAGER_TYPE,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_11[0]"          -> FEDERAL_TAX_WITHHELD,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_12[0]"          -> TRANSACTION,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_13[0]"          -> RACE,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_15[0]"          -> CASHIER,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_16[0]"          -> WINNER_SSN,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_17[0]"          -> WINDOW,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_18[0]"          -> FIRST_ID,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_19[0]"          -> SECOND_ID,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_20[0]"          -> STATE_ID_NO,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_21[0]"          -> STATE_WINNINGS,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_23[0]"          -> LOCAL_WINNINGS,
    "topmostSubform[0].CopyB[0].Col_Right[0].f1_25[0]"          -> LOCALITY_NAME,
    "topmostSubform[0].CopyB[0].CopyBHeader[0].f1_01[0]"        -> CALENDAR_YEAR,
    "topmostSubform[0].CopyC[0].Col_Left[0].f1_02[0]"           -> PAYER_ADDRESS,
    "topmostSubform[0].CopyC[0].Col_Left[0].f1_03[0]"           -> PAYER_TAX_ID,
    "topmostSubform[0].CopyC[0].Col_Left[0].f1_04[0]"           -> PAYER_TEL_NB,
    "topmostSubform[0].CopyC[0].Col_Left[0].f1_05[0]"           -> WINNER_NAME,
    "topmostSubform[0].CopyC[0].Col_Left[0].f1_06[0]"           -> WINNER_STREET_ADDRESS,
    "topmostSubform[0].CopyC[0].Col_Left[0].f1_07[0]"           -> WINNER_CITY_TOWN,
    "topmostSubform[0].CopyC[0].Col_Right[0].Box15[0].f1_22[0]" -> STATE_TAX_WITHHELD,
    "topmostSubform[0].CopyC[0].Col_Right[0].Box17[0].f1_24[0]" -> LOCAL_TAX_WITHHELD,
    "topmostSubform[0].CopyC[0].Col_Right[0].Box1[0].f1_08[0]"  -> REPORTABLE_WINNINGS,
    "topmostSubform[0].CopyC[0].Col_Right[0].Box7[0].f1_14[0]"  -> WINNINGS_FROM_IDENTICAL_WAGERS,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_09[0]"          -> DATE_WON,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_10[0]"          -> WAGER_TYPE,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_11[0]"          -> FEDERAL_TAX_WITHHELD,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_12[0]"          -> TRANSACTION,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_13[0]"          -> RACE,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_15[0]"          -> CASHIER,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_16[0]"          -> WINNER_SSN,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_17[0]"          -> WINDOW,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_18[0]"          -> FIRST_ID,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_19[0]"          -> SECOND_ID,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_20[0]"          -> STATE_ID_NO,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_21[0]"          -> STATE_WINNINGS,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_23[0]"          -> LOCAL_WINNINGS,
    "topmostSubform[0].CopyC[0].Col_Right[0].f1_25[0]"          -> LOCALITY_NAME,
    "topmostSubform[0].CopyC[0].CopyCHeader[0].f1_01[0]"        -> CALENDAR_YEAR,
    "topmostSubform[0].CopyD[0].Col_Left[0].f1_02[0]"           -> PAYER_ADDRESS,
    "topmostSubform[0].CopyD[0].Col_Left[0].f1_03[0]"           -> PAYER_TAX_ID,
    "topmostSubform[0].CopyD[0].Col_Left[0].f1_04[0]"           -> PAYER_TEL_NB,
    "topmostSubform[0].CopyD[0].Col_Left[0].f1_05[0]"           -> WINNER_NAME,
    "topmostSubform[0].CopyD[0].Col_Left[0].f1_06[0]"           -> WINNER_STREET_ADDRESS,
    "topmostSubform[0].CopyD[0].Col_Left[0].f1_07[0]"           -> WINNER_CITY_TOWN,
    "topmostSubform[0].CopyD[0].Col_Right[0].Box15[0].f1_22[0]" -> STATE_TAX_WITHHELD,
    "topmostSubform[0].CopyD[0].Col_Right[0].Box17[0].f1_24[0]" -> LOCAL_TAX_WITHHELD,
    "topmostSubform[0].CopyD[0].Col_Right[0].Box1[0].f1_08[0]"  -> REPORTABLE_WINNINGS,
    "topmostSubform[0].CopyD[0].Col_Right[0].Box7[0].f1_14[0]"  -> WINNINGS_FROM_IDENTICAL_WAGERS,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_09[0]"          -> DATE_WON,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_10[0]"          -> WAGER_TYPE,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_11[0]"          -> FEDERAL_TAX_WITHHELD,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_12[0]"          -> TRANSACTION,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_13[0]"          -> RACE,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_15[0]"          -> CASHIER,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_16[0]"          -> WINNER_SSN,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_17[0]"          -> WINDOW,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_18[0]"          -> FIRST_ID,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_19[0]"          -> SECOND_ID,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_20[0]"          -> STATE_ID_NO,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_21[0]"          -> STATE_WINNINGS,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_23[0]"          -> LOCAL_WINNINGS,
    "topmostSubform[0].CopyD[0].Col_Right[0].f1_25[0]"          -> LOCALITY_NAME,
    "topmostSubform[0].CopyD[0].CopyDHeader[0].f1_01[0]"        -> ""
  )
}
